title: Impossible Robotics
description: >-
  Welcome to the official Impossible Robotics blog site!
  Here you can find the latest news, stories and much more!
baseurl: ""
url: ""

permalink: ./:year-:month-:day/:title/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
    
# Build settings
plugins:
  - jekyll-feed
